name: Release Please

on:
  push:
    branches: [master]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: '@schummar/runp'

      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
        if: ${{ steps.release.outputs.release_created }}

      - run: pnpm i --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
